<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.4.3" />
    <PackageReference Include="MSTest.TestFramework" Version="3.4.3" />
    <PackageReference Include="coverlet.collector" Version="6.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenTibia.Common\OpenTibia.Common.csproj" />
    <ProjectReference Include="..\OpenTibia.Game\OpenTibia.Game.csproj" />
    <ProjectReference Include="..\OpenTibia.IO\OpenTibia.IO.csproj" />
    <ProjectReference Include="..\OpenTibia.Security\OpenTibia.Security.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="data\server\config.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>

